package day3;

public class blackbox extends loadrunner{
	

	public static void main(String[] args) {
		// TODO Auto-generated method stub
//blackbox black=new blackbox();
//black.test();
//black.testcases();
		loadrunner load= new blackbox();
		load.testcases();
		load=new selenium();
		load.testcases();
	}
public void testcases()
{
	System.out.println("generated by user as well as automatic");
}
}
class selenium extends loadrunner
{
	public void testcases()
	{
	System.out.println("selenium auto");
}
}


abstract class loadrunner{
	public void test()
	{
		System.out.println("load capacity of site");
	}
	abstract public void  testcases();
}
